image_topic_1: "/arena_camera_node/image_raw/compressed"
image_topic_2: "/arena_camera_node_2/image_raw/compressed"
image_topic_3: "/usb_cam/image_color/compressed"
odom_topic_1: "/a2_tractor_etalin/odometry"
odom_topic_2: "/a2_trailer_etalin/odometry"
imu_topic_1: "/vectornav/IMU"
steer_topic: "/j1939can_node/steer_angle"
vel_topic: "/j1939can_node/vehicle_speed"
# imu_topic_2: "/imu_2"
output_topic: "/synced_output"